<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<script>
        require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'rocketfuel'
            };
            layout([
                {
                    component: 'RKFL_Rocketfuel/js/view/payment/method-renderer/multishipping/rocketfuel',
                    name: 'payment_method_rocketfuel',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
