<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<script>
        require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'rocketfuel'
            };
            layout([
                {
                    component: 'PayPal_Braintree/js/view/payment/method-renderer/multishipping/paypal',
                    name: 'payment_method_rocketfuel',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            $('body').trigger('contentUpdated');
        })
    })
    // require([
    //     'uiLayout',
    //     'jquery'
    // ], function (layout, $) {
    //     $(function () {
    //         var paymentMethodData = {
    //             method: 'braintree_paypal'
    //         };
    //         layout([
    //             {
    //                 component: 'PayPal_Braintree/js/view/payment/method-renderer/multishipping/paypal',
    //                 name: 'payment_method_braintree_paypal',
    //                 method: paymentMethodData.method,
    //                 item: paymentMethodData
    //             }
    //         ]);

    //         $('body').trigger('contentUpdated');
    //     })
    // })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
