<?php
$order = $block->getOrder();
// var_dump($order );
?>
<?php if ($block->isNotPayed()) : ?>
    <div id="rocketfuel-iframe-container">
        <div id="rocketfuel-drag">
            <div id="rocketfuel-dragheader"></div>
        </div>
        <iframe id="rocketfuel-iframe" src="<?php echo $block->getIframeUrl() ?>"
                onload="rocketRun(<?php echo $order->getId() ?>)">
        </iframe>
    </div>
    <button
        class="action primary"
        onclick="rocketRun(<?php echo $order->getId() ?>)"
    >
        <?php echo __('Pay with/on Rocketfuel') ?>
    </button>
    <style>
        #rocketfuel-drag:active {
            cursor: grabbing;
        }

        #rocketfuel-drag:active + #rocketfuel-iframe {
            box-shadow: 0px 4px 7px rgba(0, 0, 0, 0.6);
            transform: scale(1.01);
        }

        #rocketfuel-plugin-div{
            max-width: 850px;
        }

        .rocketfuel-hidden{
            display: none;
        }

        .rocketfuel-overlay{
            z-index: 100;
            padding: 150px;
            position: fixed;
            background-color: rgba(60, 60, 60, 0.47);
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;

        }

        .rocketfuel-overlay-pugin-block{
            background-color: white;
        }

        #rocketfuel-drag {
            width: 210px;
            height: 60px;
            margin-right: 155px;
            top: 10px;
            right: 10px;
            background: transparent;
            position: fixed;
            z-index: 10001 !important;
            cursor: pointer;
        }
        #rocketfuel-drag:active {
            cursor: grabbing;
        }
        #rocketfuel-drag:active + #rocketfuel-iframe {
            box-shadow: 0px 4px 7px rgba(0, 0, 0, 0.6);
            transform: scale(1.01);
        }
        #rocketfuel-dragheader {
            width: 100%;
            height: 100%;
        }
        #rocketfuel-iframe {
            border: 0px;
            /*margin: auto;*/
            padding: 0px;
            overflow: hidden;
            width: 365px !important;
            height: 700px;
            top: 10px;
            right: 10px;
            box-shadow: 0px 4px 7px rgba(0, 0, 0, 0.3);
            border-radius: 2px;
            transition: height 0.5s ease, box-shadow 250ms ease-in-out 0s, transform 250ms cubic-bezier(0.25, 0.8, 0.25, 1) 0s;
            clip: auto !important;
            display: block !important;
            opacity: 1 !important;
            position: fixed !important;
            z-index: 10000 !important;
            transform: translate3d(0px, 0px, 0px);
        }
    </style>

<?php endif ?>