<?php

/**
 * Paystack Magento2 Module using \Magento\Payment\Model\Method\AbstractMethod
 * Copyright (C) 2019 Paystack.com
 * 
 * This file is part of RKFL/Rocketfuel
 * 
 * RKFL/Rocketfuel is free software => you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http =>//www.gnu.org/licenses/>.
 */

?>
<script src="https://d3rpjm0wf8u2co.cloudfront.net/static/rkfl.js"></script>
<!-- <script src="https://qa-woocommerce.rocketdemo.net/wp-content/plugins/rocketfuel-payment-gateway/assets/js/rkfl.js?ver=1646670115"></script> -->
<!-- <script src="https://qa-woocommerce.rocketdemo.net/wp-content/plugins/rocketfuel-gateway-woocommerce/assets/js/rkfl.js?ver=1647304534"></script> -->
<!-- <script src="https://businesstosales.com/blog/wp-content/plugins/rocketfuel-gateway-woocommerce/assets/js/rkfl.js?ver=0.89942000%201647414469"></script> -->
<script>
    var BASE_URL = '<?= $block->escapeUrl($block->getBaseUrl()) ?>';
    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>




